### ISSUE TITLE
Cursor color is black

### ISSUE THREAD

**Issue by zeyu42** [Toyonut/tilix_pop_os_theme#1]
The cursor color is now black (in the default gnome terminal it is white) and hardly visible on a dark background. I had to manually change it from the profile.

**Comment by Toyonut** [comment]
It should be blue with this theme. I did notice that if I changed it to a different color, the cursor color would stick for some reason to whatever color I had set. I can see here https://github.com/storm119/Tilix-Themes that none of the themes set the advanced properties. 
Can you export your change and paste it in here? should just be a small json file. Otherwise I will remove the advanced properties which should also fix it.

**Comment by leonzhu42** [comment]
`{
    "background-color": "#333333",
    "badge-color": "#FFFFFF",
    "bold-color": "#FFFFFF",
    "comment": "",
    "cursor-background-color": "#FFFFFF",
    "cursor-foreground-color": "#FFFFFF",
    "foreground-color": "#F2F2F2",
    "highlight-background-color": "#FFFFFF",
    "highlight-foreground-color": "#FFFFFF",
    "name": "Custom",
    "palette": [
        "#333333",
        "#CC0000",
        "#4E9A06",
        "#C4A000",
        "#3465A4",
        "#75507B",
        "#06989A",
        "#D3D7CF",
        "#88807C",
        "#F15D22",
        "#73C48F",
        "#FFCE51",
        "#48B9C7",
        "#AD7FA8",
        "#34E2E2",
        "#EEEEEC"
    ],
    "use-badge-color": false,
    "use-bold-color": true,
    "use-cursor-color": true,
    "use-highlight-color": true,
    "use-theme-colors": false
}`

**Comment by zeyu42** [comment]
`
{
    "background-color": "#333333",
    "badge-color": "#FFFFFF",
    "bold-color": "#FFFFFF",
    "comment": "",
    "cursor-background-color": "#FFFFFF",
    "cursor-foreground-color": "#FFFFFF",
    "foreground-color": "#F2F2F2",
    "highlight-background-color": "#FFFFFF",
    "highlight-foreground-color": "#FFFFFF",
    "name": "Custom",
    "palette": [
        "#333333",
        "#CC0000",
        "#4E9A06",
        "#C4A000",
        "#3465A4",
        "#75507B",
        "#06989A",
        "#D3D7CF",
        "#88807C",
        "#F15D22",
        "#73C48F",
        "#FFCE51",
        "#48B9C7",
        "#AD7FA8",
        "#34E2E2",
        "#EEEEEC"
    ],
    "use-badge-color": false,
    "use-bold-color": true,
    "use-cursor-color": true,
    "use-highlight-color": true,
    "use-theme-colors": false
}
`

**Comment by Toyonut** [comment]
Thanks, I have just pushed a change to disable the advanced color options. The colors are set, but not enabled by default. So the cursor color is set by the foreground color now.

**Comment by zeyu42** [comment]
Thanks for the great job! :+1: :+1:
